{
 "title": "Hashicorp Vault - Integrated storage (Raft)",
 "description": " Hashicorp Vault with Integrated storage (Raft) Metrics",
 "tags": [
  "vault",
  "integrated-storage-raft"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(up{job=~\".+/vault\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(up{job=~\".+/vault\",instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": "label_values(vault_secret_kv_count, mount_point)"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_autopilot_healthy{}", "legendFormat": "Leader: {{ instance }}" }
   ]
  },
  {
   "title": "Fault tolerance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance{}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count{})",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\".+/vault\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "mountpoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_token_count)" }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 15 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy)",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count - vault_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl)",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation)",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count)",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Election Events",
   "type": "status-history",
   "description": "This panel should show no activity in a stable cluster. Some leadership transition events are expected, such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "increase(vault_raft_state_candidate{}[1m]) > 0",
     "legendFormat": "{{ instance }} - candidate"
    },
    {
     "expr": "increase(vault_raft_state_leader{}[1m]) > 0",
     "legendFormat": "{{ instance }} - leader"
    }
   ]
  },
  {
   "title": "Leader Last Contacted",
   "type": "timeseries",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_leader_lastContact{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Log replication from leader to servers",
   "type": "timeseries",
   "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul servers, as well as the performance of the communication between the servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_replication_appendEntries_rpc{quantile=\"0.9\"}",
     "legendFormat": "Peer ID: {{ peer_id }}"
    }
   ]
  },
  {
   "title": "Raft Replication Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_replication_heartbeat{quantile=\"0.9\"}",
     "legendFormat": "Peer ID: {{ peer_id }}"
    }
   ]
  },
  { "title": "Integrated storage (Raft)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Write logs",
   "type": "timeseries",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_leader_dispatchLog", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Leader Commit time",
   "type": "timeseries",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_commitTime", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Raft Dispatch Log",
   "type": "timeseries",
   "description": "Time to write log, mark in flight, and start replication to followers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_leader_dispatchLog{quantile=\"0.9\"}",
     "legendFormat": "Time"
    },
    {
     "expr": "increase(vault_raft_leader_dispatchNumLogs{}[$__rate_interval])",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_commitTime", "legendFormat": "{{ quantile }}" }
   ]
  },
  {
   "title": "Raft FSM apply",
   "type": "timeseries",
   "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_fsm_applyBatch{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Append Entries",
   "type": "timeseries",
   "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_rpc_appendEntries{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(vault_raft_apply{}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "bargauge",
   "description": "Current index applied to FSM",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_raft_storage_stats_applied_index{}",
     "legendFormat": "Peer ID: {{ peer_id }}"
    }
   ]
  },
  {
   "title": "Stats: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "repeat": "node",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{instance=~\"$node\"} / vault_runtime_malloc_count{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 6, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{instance=~\"$node\"})",
       "legendFormat": "$node"
      }
     ]
    }
   ]
  }
 ]
}